---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: myapp-config
  namespace: flux-system
spec:
  dependsOn: 
    - name: podinfo
  interval: 5m0s
  path: ./config
  prune: true
  sourceRef:
    kind: GitRepository
    name: myapp
  targetNamespace: default
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: myapp-deployment
  namespace: flux-system
spec:
  dependsOn: 
    - name: myapp-config
    - name: podinfo
  interval: 5m0s
  path: ./deployment
  prune: true
  sourceRef:
    kind: GitRepository
    name: myapp
  targetNamespace: default


