---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: myapp
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/bacherfl/my-k8s-app
